# Generated by Django 5.2.1 on 2025-05-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='img',
            field=models.ImageField(default='student_photos/default.jpg', upload_to='student_photos/'),
            preserve_default=False,
        ),
    ]
